services:
  backend:
    build:
      context: ../
      dockerfile: dev-config/Dockerfile.backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    volumes:
      - ../backend:/app      
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} 
      - CLIENT_URL=http://localhost:${CLIENT_PORT}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}
      - VKONTAKTE_CLIENT_ID=${VKONTAKTE_CLIENT_ID}
      - VKONTAKTE_CLIENT_SECRET=${VKONTAKTE_CLIENT_SECRET}
      - SERVER_URL=${SERVER_URL}
  db_postgres:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

